// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/Portfolio": {
    params: {};
  };
  "/Portfolio/projects/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/Portfolio" | "/Portfolio/projects/:id";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/Portfolio";
  };
  "routes/projectDetail.jsx": {
    id: "routes/projectDetail";
    page: "/Portfolio/projects/:id";
  };
};